# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-10-10 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_remove_reply_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default='not applicable', max_length=200),
        ),
    ]
