# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-10-10 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_doctor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.CharField(default='not given', max_length=300),
        ),
    ]
