# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-10-10 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20211010_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='basic_app.Comment')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Doctor')),
            ],
        ),
    ]
